### PR TITLE
Reviews import

### PR DESCRIPTION
**Pull request by danielSanchezQ**
Simple command that takes the vCA aggregated file and exports a csv/json file with the data ready for being imported into the VitSS DB.

### CODE REVIEW

**Comment by dkijania** [comment]
I think a single test on example vca and assertion on output will do. I will take care of automated e2e tests in vit-testing project

**Comment by danielSanchezQ** [comment]
@dkijania I added a simple test checking number of lines for output.

**Review by Zeegomo — COMMENTED** [review]
What about using csv instead of the proprietary xlsx format? I see no advantage in having that, especially since we only use a single file anyway, at least in my understanding

**Comment by danielSanchezQ** [comment]
> What about using csv instead of the proprietary xlsx format? I see no advantage in having that, especially since we only use a single file anyway, at least in my understanding

@Zeegomo you are right. At the beginning was because there were a chance of the need to read 2 sheets. But finally we just needed one. I will change that.

**Comment by danielSanchezQ** [comment]
Superseded by #58

**Pull request closed without merging**
